TOP=../..
include $(TOP)/configure/CONFIG


#optimization of db files using dbst(DEFAULT:NO)
#DB_OPT=YES

DB+=NDPlugin{{ cookiecutter.plugin_name }}.template


include $(TOP)/configure/RULES

#----------------------------------------